name: farmers
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Fix Git permissions
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # Set up DVC
      - uses: iterative/setup-dvc@v1

      # Configure DVC auto-staging (optional)
      - name: Configure DVC
        run: dvc config core.autostage true
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro 

          git fetch --prune
          dvc metrics diff --md master > report.md

          # Add figure to the report
          echo "## Validating results by region"
          echo "![](./by_region.png)" >> report.md
          cml comment create report.md
